# Databricks notebook source
# DBTITLE 1,Cell 1: Environment Setup & Package Installation
# MAGIC %pip install sentence-transformers

# COMMAND ----------
# DBTITLE 1,Cell 2: Import Libraries & Configure Spark Session
import os
import pandas as pd
from typing import Iterator
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, udf, explode, pandas_udf
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, ArrayType, FloatType

# Ensure local testing compatibility if run outside a Databricks environment
spark = SparkSession.builder \
    .appName("RAG-PySpark-Pipeline") \
    .config("spark.sql.execution.arrow.pyspark.enabled", "true") \
    .config("spark.sql.execution.arrow.maxRecordsPerBatch", "2048") \
    .getOrCreate()

print(f"Spark Session Active. Arrow Execution Enabled: {spark.conf.get('spark.sql.execution.arrow.pyspark.enabled')}")

# COMMAND ----------
# DBTITLE 1,Cell 3: Ingestion Layer (Raw Landing Zone / Bronze Table)
# Create a comprehensive mock dataset simulating an unstructured raw Data Lake landing zone.
# The documents cover advanced data engineering and AI engineering architecture topics.
mock_raw_data = [
    (
        "doc_001",
        "Spark Architecture Overview",
        "Apache Spark is a multi-language engine for executing data engineering, data science, and machine learning on single-node machines or clusters. It features a master-worker architecture where a driver program coordinates tasks across executor nodes. The driver is responsible for running the application's main() function and building the Logical and Physical Query Plans. Executors run on worker nodes and are responsible for executing individual tasks and caching data. Databricks automates cluster creation and management, allowing these processes to scale seamlessly.",
        "Architecture"
    ),
    (
        "doc_002",
        "Delta Lake Transaction Log Deep Dive",
        "Delta Lake is an open-source storage framework that enables building Lakehouse architectures on top of cloud object storage. At the heart of Delta Lake's ACID compliance is its transaction log, known as the _delta_log. Every transaction made to a Delta Table is written as an ordered JSON file inside this directory. These commit files record actions such as adding files, removing files, and updating metadata. When a query reads a Delta Table, Spark reconstructs the latest state by reading these commits sequentially, ensuring snapshot isolation and auditability.",
        "Storage"
    ),
    (
        "doc_003",
        "Retrieval-Augmented Generation (RAG) Systems",
        "Retrieval-Augmented Generation (RAG) is an architectural pattern that optimizes the output of a Large Language Model (LLM) by referencing an authoritative external knowledge base before generating a response. Traditional LLMs suffer from knowledge cutoff dates and hallucination problems. RAG solves this by converting user queries into vectors, searching a vector database for relevant contexts, and appending those contexts to the prompt. The LLM then synthesizes an answer grounded in the retrieved documents, improving accuracy.",
        "AI/ML"
    ),
    (
        "doc_004",
        "Vector Databases and Semantic Search",
        "Vector databases are specialized storage systems designed to handle high-dimensional vector representations of unstructured data. Traditional databases use keyword indexes to search text, which fails to capture synonyms or semantic intent. In contrast, vector databases index dense float arrays generated by deep learning models. By measuring mathematical distance (such as Cosine Similarity or Euclidean Distance), vector databases retrieve items that are semantically similar to a query, even if no identical words exist.",
        "AI/ML"
    )
]

# Define the ingestion schema for the raw Bronze layer
bronze_schema = StructType([
    StructField("doc_id", StringType(), False),
    StructField("title", StringType(), False),
    StructField("text", StringType(), False),
    StructField("category", StringType(), False)
])

# Create the PySpark DataFrame
bronze_df = spark.createDataFrame(mock_raw_data, schema=bronze_schema)

print("Bronze Landing Zone DataFrame created. Count: ", bronze_df.count())
bronze_df.show(5, truncate=50)

# COMMAND ----------
# DBTITLE 1,Cell 4: Text Chunking Layer (Silver Processing)
# Define a standard Python function to split text into semantic overlapping windows.
# Targets roughly 500 characters with a 50-character overlap.
def chunk_unstructured_text(text: str, chunk_size: int = 500, overlap: int = 50) -> list:
    """
    Splits unstructured text into fixed-size overlapping semantic chunks.
    Returns a list of dictionaries containing chunk indices and character lengths.
    """
    if not text or len(text.strip()) == 0:
        return []
    
    chunks = []
    start = 0
    idx = 0
    text_len = len(text)
    
    while start < text_len:
        # Determine end index
        end = min(start + chunk_size, text_len)
        
        # Pull current window
        chunk = text[start:end]
        
        chunks.append({
            "chunk_index": idx,
            "chunk_text": chunk,
            "char_length": len(chunk)
        })
        
        idx += 1
        
        # Break condition if we've reached the end
        if end == text_len:
            break
            
        # Shift start pointer forward by chunk size minus the desired overlap
        start += (chunk_size - overlap)
        
    return chunks

# Define the PySpark Schema representation for the output chunks array
chunk_struct_schema = ArrayType(StructType([
    StructField("chunk_index", IntegerType(), False),
    StructField("chunk_text", StringType(), False),
    StructField("char_length", IntegerType(), False)
]))

# Wrap the text chunker in a standard PySpark UDF
chunking_udf = udf(lambda t: chunk_unstructured_text(t), chunk_struct_schema)

# Apply chunking and explode the array column to transform documents into row-level semantic chunks
silver_df = bronze_df.withColumn("chunks", chunking_udf(col("text"))) \
    .select("doc_id", "title", "category", explode("chunks").alias("chunk")) \
    .select(
        "doc_id",
        "title",
        "category",
        col("chunk.chunk_index").alias("chunk_index"),
        col("chunk.chunk_text").alias("chunk_text"),
        col("chunk.char_length").alias("char_length")
    )

print("Silver Chunked DataFrame created. Total Chunks: ", silver_df.count())
silver_df.show(10, truncate=50)

# COMMAND ----------
# DBTITLE 1,Cell 5: The AI/Vectorization Layer Boundary
# ==============================================================================
# 🛑 END OF TRADITIONAL PYSPARK ETL LAYER (Text Ingestion, Cleaning & Chunking)
# ==============================================================================
# 🚀 START OF DISTRIBUTED AI & VECTOR EMBEDDING GENERATION LAYER
# ==============================================================================
#
# Technical Highlights:
# 1. We leverage a PySpark Vectorized Pandas UDF (Series-to-Series) to process
#    chunks in batches using Apache Arrow memory formats instead of row-by-row.
# 2. To optimize memory usage, the sentence-transformers model is loaded exactly
#    ONCE per executor worker process (lazy-loaded singleton pattern), avoiding
#    exceeding container RAM limitations on free-tier single-node clusters.
# 3. PyTorch utilizes vectorized batch inference automatically when list inputs
#    are passed to the sentence-transformer encode() interface.
#
# ==============================================================================

# Define a global placeholder to implement the lazy-loaded model singleton pattern
_sentence_transformer_model = None

def get_sentence_transformer_model():
    """
    Ensures that the model weights are loaded into CPU memory exactly once
    per worker process session. subsequent evaluations reuse the cached model.
    """
    global _sentence_transformer_model
    if _sentence_transformer_model is None:
        from sentence_transformers import SentenceTransformer
        # Load the lightweight MiniLM model (384-dimensional dense vectors)
        # Highly efficient for Single-Node clusters (Databricks Community Edition)
        _sentence_transformer_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    return _sentence_transformer_model

@pandas_udf(ArrayType(FloatType()))
def generate_batch_embeddings_udf(sentences: pd.Series) -> pd.Series:
    """
    Vectorized PySpark UDF.
    Transforms an Arrow-backed Pandas Series of strings into an Arrow-backed 
    Pandas Series of Float arrays representing dense vector embeddings.
    """
    # 1. Fetch our lazy-loaded model singleton
    model = get_sentence_transformer_model()
    
    # 2. Extract raw text list from the Pandas Series
    text_list = sentences.tolist()
    
    # 3. Generate high-dimensional vector embeddings in a single parallelized pass
    #    (SentenceTransformers executes highly optimized batched PyTorch inference)
    embeddings = model.encode(text_list, show_progress_bar=False)
    
    # 4. Map the resulting 2D NumPy array back into a Pandas Series of native lists
    return pd.Series(list(embeddings))

# COMMAND ----------
# DBTITLE 1,Cell 6: Gold Layer Generation & Delta Lake Managed Storage
# Generate dense vector embeddings across our chunked dataset in parallel
gold_df = silver_df.withColumn("vector_embeddings", generate_batch_embeddings_udf(col("chunk_text")))

# Write the final schema with embeddings to a managed Delta Lake table in the Databricks default catalog.
# In Databricks, saving as table automatically handles the storage metadata and ACID guarantees.
target_table_name = "default.rag_vector_store"

# Overwrite mode allows notebook re-runs without schema conflict errors
gold_df.write \
    .format("delta") \
    .mode("overwrite") \
    .option("overwriteSchema", "true") \
    .saveAsTable(target_table_name)

print(f"Gold Vector Store Table '{target_table_name}' successfully persisted to Delta Lake.")

# COMMAND ----------
# DBTITLE 1,Cell 7: Query Verification & Database Validation
# Read back the saved table from Delta Lake using Spark SQL to verify schema integrity.
verification_df = spark.read.table("default.rag_vector_store")

print("\n--- SCHEMA OF MANAGED DELTA TABLE ---")
verification_df.printSchema()

# Run a validation query checking array dimension size
print("\n--- DATA PREVIEW (TOP 5 CHUNKS WITH EMBEDDINGS) ---")
from pyspark.sql.functions import size
verification_df.select(
    "doc_id",
    "chunk_index",
    col("chunk_text").substr(1, 40).alias("truncated_text"),
    "char_length",
    size("vector_embeddings").alias("vector_dimension")
).show(5, truncate=False)
