import pytest
import numpy as np

# Import chunking logic from the main pipeline notebook
from rag_pipeline_notebook import chunk_unstructured_text

def test_chunking_split_bounds():
    """
    Verifies that the text chunker splits a document into chunks 
    that do not exceed the specified maximum character size.
    """
    sample_text = (
        "Apache Spark is a multi-language engine for executing data engineering, "
        "data science, and machine learning. It features a master-worker architecture."
    )
    chunk_size = 50
    overlap = 10
    
    chunks = chunk_unstructured_text(sample_text, chunk_size=chunk_size, overlap=overlap)
    
    assert len(chunks) > 0, "No chunks were generated."
    for chunk in chunks:
        assert chunk["char_length"] <= chunk_size, f"Chunk size {chunk['char_length']} exceeds limit of {chunk_size}!"
        assert len(chunk["chunk_text"]) == chunk["char_length"], "Character length field mismatch with actual text length!"


def test_chunking_overlap_mathematics():
    """
    Validates that the sliding window overlap algorithm is mathematically correct.
    Specifically, the last 'overlap' characters of Chunk N must match the first 
    'overlap' characters of Chunk N+1.
    """
    sample_text = (
        "Retrieval-Augmented Generation (RAG) is an architectural pattern that "
        "optimizes the output of a Large Language Model (LLM) by referencing an "
        "authoritative external knowledge base before generating a response."
    )
    chunk_size = 100
    overlap = 15
    
    chunks = chunk_unstructured_text(sample_text, chunk_size=chunk_size, overlap=overlap)
    
    assert len(chunks) > 1, "Not enough chunks generated to verify overlap."
    
    for i in range(len(chunks) - 1):
        chunk_n = chunks[i]["chunk_text"]
        chunk_np1 = chunks[i+1]["chunk_text"]
        
        # Extract overlapping text regions
        overlap_n = chunk_n[-overlap:]
        overlap_np1 = chunk_np1[:overlap]
        
        assert overlap_n == overlap_np1, f"Overlap mismatch between chunk {i} and chunk {i+1}!"


def test_cosine_similarity_calculation():
    """
    Verifies that dot product similarity behaves correctly.
    Since embeddings generated by MiniLM are unit-normalized, the dot product
    must equal 1.0 for identical vectors, and be between -1.0 and 1.0 for others.
    """
    # Create two arbitrary mock normalized vectors of dimension 4
    vec_a = np.array([0.5, 0.5, 0.5, 0.5])  # L2 norm = sqrt(0.25*4) = 1.0
    vec_b = np.array([0.5, 0.5, 0.5, 0.5])
    
    # Calculate dot product
    sim_self = float(np.dot(vec_a, vec_b))
    assert pytest.approx(sim_self, 0.0001) == 1.0, "Cosine similarity of identical unit vectors must be 1.0!"
    
    # Orthogonal vectors
    vec_c = np.array([0.7071, 0.7071, 0.0, 0.0])  # Norm = 1.0
    vec_d = np.array([0.0, 0.0, 0.7071, 0.7071])  # Norm = 1.0
    sim_ortho = float(np.dot(vec_c, vec_d))
    assert pytest.approx(sim_ortho, 0.0001) == 0.0, "Cosine similarity of orthogonal vectors must be 0.0!"


def test_prompt_construction():
    """
    Verifies that prompt building correctly formats retrieved context and query strings.
    """
    user_query = "What is Spark?"
    mock_chunks = [
        {"title": "Doc 1", "chunk_text": "Spark is a distributed computing engine."},
        {"title": "Doc 2", "chunk_text": "Spark runs on cluster nodes."}
    ]
    
    # Formatting context
    context_str = ""
    for idx, row in enumerate(mock_chunks):
        context_str += f"[Context {idx + 1} | Source: {row['title']}]\n{row['chunk_text']}\n\n"
        
    rag_prompt = f"""Use the context below to answer: {user_query}
Context:
{context_str}"""
    
    assert user_query in rag_prompt, "Query string missing from prompt!"
    assert "Doc 1" in rag_prompt, "Metadata source missing from prompt!"
    assert "Doc 2" in rag_prompt, "Metadata source missing from prompt!"
    assert "Spark is a distributed computing engine." in rag_prompt, "Context text missing from prompt!"
